### ISSUE TITLE
Problems with connecting to database and editing data.

### ISSUE THREAD

**Issue by nadman3** [javaWorkspace/Campus#2]
Latest commit is on [startWritingTests](https://github.com/javaWorkspace/Campus/tree/startWritingTests) branch. I created all functions in services but I haven't found information anywhere how is correctly to edit, connect and delete data from h2 database. In my tests every time I have incorrect results and I can't understand why. Could not you please look at the code and keep their notes and tips.

**Comment by SvNevmerzhytska** [comment]
The first problem that I faced is that I don't have data you're trying to use in the tests. That's why you should add some SQL files to populate data used in tests and configure your tests in such way that this data will be added to DB before the test run.

**Comment by SvNevmerzhytska** [comment]
If you look into the logs during a test run, you will see that before each test database is recreating but without data, because data added to the database only once (see @BeforeClass annotation).
Remove @BeforeClass and static modifier, rename method and call it in before method to populate test data for every test.

**Comment by nadman3** [comment]
@SvNevmerzhytska thank you for answer! I've fixed creating tests but now I have unexplained problems. `java.lang.ArrayIndexOutOfBoundsException: -1` in `public void getMiddleMarkPerCourse()`. But when I use simple function in `public void getMiddleMarkPerYear()` - everything is OK. And something interesting with 'public void deleteCourse()".

**Comment by nadman3** [comment]
I'm saving collection of  java.lang.Double like in [documentation](http://docs.jboss.org/hibernate/core/3.6/reference/en-US/html/collections.html#collections-ofvalues) (7.2.3. Collections of basic types and embeddable objects). I'm adding to list correctly, but database with list is still empty. 
![Student in preparing method](https://cloud.githubusercontent.com/assets/12157875/16870141/b9b6b060-4a88-11e6-8d8d-80b9e7d0d72f.png) 
![Student in getAllMarks method](https://cloud.githubusercontent.com/assets/12157875/16870461/51580b52-4a8a-11e6-87a6-15e2c6290a36.png)

I think that problem is when I'm trying to get **Student** from list of **Students** in **Course.** 
Perhaps the problem lies in the fact that the circuit that I want to get an assessment is too long

I am looking for a week this error in code and I really don't know what to do. @SvNevmerzhytska I need your help ;(

**Comment by nadman3** [comment]
@SvNevmerzhytska now I'm remaking to annotation-config app and DAO to Spring Data. May you help me finish configuration because I can't find something about Spring Data with console app? In [startWritingTests](https://github.com/javaWorkspace/Campus/tree/startWritingTests) branch is not working current version.
